### ISSUE TITLE
Deploy vCluster using CLI on Mac OS has small correction: download come before version

### ISSUE THREAD

**Issue by vijaypolsani** [loft-sh/vcluster-docs#267]
https://github.com/loft-sh/vcluster-docs/blame/6e146184f7013b52b1d61cc71a870094aca7e3ed/vcluster/_partials/deploy/install-cli-beta.mdx#L30

Deploy vCluster using CLI on Mac OS has small correction: **_download come before version_**
**Current:**
`curl -L -o vcluster "https://github.com/loft-sh/vcluster/releases/<VCLUSTER_VERSION>/download/vcluster-darwin-amd64" && sudo install -c -m 0755 vcluster /usr/local/bin && rm -f vcluster`

**ToBe:**
`curl -L -o vcluster "https://github.com/loft-sh/vcluster/releases/download/<VCLUSTER_VERSION>/vcluster-darwin-arm64" && sudo install -c -m 0755 vcluster /usr/local/bin && rm -f vcluster`
**_example:_**
`curl -L -o vcluster "https://github.com/loft-sh/vcluster/releases/download/v0.20.0/vcluster-darwin-arm64" && sudo install -c -m 0755 vcluster /usr/local/bin && rm -f vcluster`

**Comment by vijaypolsani** [comment]
Could have raised PR but still in the initial steps

**Comment by Piotr1215** [comment]
Thank you for raising the issue @vijaypolsani , I'm going to close it as it was already fixed in a [different PR](https://github.com/loft-sh/vcluster-docs/pull/336).
